server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8088

logging:
    file: vcats-led.log 

spring:
    application:
        name:  vcats-led
    profiles:
        active: dev
        
mybatis:
    mapper-locations: 'classpath:mapper/*.xml'
    
#  Mapper 
mapper:
    mappers:
    - tk.mybatis.mapper.common.Mapper
    notEmpty: true
    identity: MYSQL
    
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


      #http client 配置
http.client:
          maxTotal: 100 #最大连接数

          defaultMaxPerRoute: 20 #并发数

          connectTimeout: 1000 #创建连接的最长时间

          connectionRequestTimeout: 500 #从连接池中获取到连接的最长时间

          socketTimeout: 10000 #数据传输的最长时间

          staleConnectionCheckEnabled: true #提交请求前测试连接是否可用



